### ISSUE TITLE
Cannot login to Azure: "We're unable to complete your request"

### ISSUE THREAD

**Issue by mythcyrax** [microsoftgraph/angular4-connect-sample#1]
AFter building the Angular4 app, I tried to test it in browser.
When I try to login, I get the error:
"We're unable to complete your request
Microsoft account is experiencing technical problems. Please try again later."

**Comment by jamescro** [comment]
Thanks for the feedback. Could you hit F12 when you run the sample and post the error that you're getting in the console?

**Comment by jamescro** [comment]
I was unassigned because I no longer work for Microsoft and therefore am no longer a member of the MicrosoftGraph organization. I'm sorry about the confusion.

**Comment by jasonjoh** [comment]
Closing due to no response
