### ISSUE TITLE
Provided sample opens a pop-up for authentication

### ISSUE THREAD

**Issue by SharmaAjay19** [microsoftgraph/angular4-connect-sample#2]
The provided sample here opens a pop-up for AAD authentication. Is it possible to do the same and get an access token without going through a pop-up(as pop-ups are usually blocked in browsers).

**Comment by jasonjoh** [comment]
We are archiving this sample as it is no longer being maintained. We're replacing it with a new sample which you can find here: https://github.com/microsoftgraph/msgraph-training-angularspa.
