### ISSUE TITLE
this.message problem

### ISSUE THREAD

**Issue by MuratGOZCU** [microsoftgraph/angular4-connect-sample#3]
Hi guys,
My problem is what can I do in giving the string, html error like the picture?

![image](https://user-images.githubusercontent.com/31828822/45413323-8dbfe500-b681-11e8-99fe-fa17c59148ed.png)

**Comment by ThorstenHans** [comment]
@MuratGOZCU couple of questions regarding your setuo:

- how is `message` typed on that class?
- which version of `@microsoft/microsoft-graph-types` is listed in `package.json`? 

If you're running the latest version from `master`, `message` is typed as `MicrosoftGraph.Message`.

The interface `Message` is derived from `OutlookItem` which again is derived from `Entity`. Finally, `Entity` defines `id` as optional property. 

I've also cloned the sample again to a clean environment

macOS `10.13.6`
nodeJS `10.5.0`

After executing `npm install` I've no warnings or errors. So it would be great to get some more insights from you

**Comment by jasonjoh** [comment]
Closing due to no response
